# Generated by Django 5.1.5 on 2025-04-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='symtoms',
            new_name='symptom',
        ),
    ]
